# Resources/config/assets.yml
animatecss:
    version: "3.7.0"

font_awesome:
    version: "5.10.1"

jquery:
    version: "3.4.1"

jquery_easy_autocomplete:
    version: "1.3.4"

jquery_input_mask:
    version: "3.3.11"

jquery_select2:
    locales:
        - "af"
        - "ar"
        - "az"
        - "bg"
        - "bs"
        - "ca"
        - "cs"
        - "da"
        - "de"
        - "dsb"
        - "el"
        - "en"
        - "es"
        - "et"
        - "eu"
        - "fa"
        - "fi"
        - "fr"
        - "gl"
        - "he"
        - "hi"
        - "hr"
        - "hsb"
        - "hu"
        - "hy"
        - "id"
        - "is"
        - "it"
        - "ja"
        - "km"
        - "ko"
        - "lt"
        - "lv"
        - "mk"
        - "ms"
        - "nb"
        - "nl"
        - "pl"
        - "ps"
        - "pt-BR"
        - "pt"
        - "ro"
        - "ru"
        - "sk"
        - "sl"
        - "sr-Cyrl"
        - "sr"
        - "sv"
        - "th"
        - "tr"
        - "uk"
        - "vi"
        - "zh-CN"
        - "zh-TW"
    version: "4.0.5"

material_design_color_palette:
    version: "1.0.1"

material_design_hierarchical_display:
    version: "1.0.1"

material_design_iconic_font:
    version: "2.2.0"

sweet_alert:
    version: "2.1.2"

wait_me:
    version: "1.19"
