# Resources/config/assets.yml
assets:

    wbw.core.asset.animate_css:
        version: "3.7.0"

    wbw.core.asset.font_awesome:
        version: "5.10.1"

    wbw.core.asset.jquery:
        version: "3.4.1"

    wbw.core.asset.jquery_easy_autocomplete:
        version: "1.3.4"

    wbw.core.asset.jquery_input_mask:
        version: "3.3.11"

    wbw.core.asset.jquery_select2:
        version: "4.0.5"
        locales:
            - "af"
            - "ar"
            - "az"
            - "bg"
            - "bs"
            - "ca"
            - "cs"
            - "da"
            - "de"
            - "dsb"
            - "el"
            - "en"
            - "es"
            - "et"
            - "eu"
            - "fa"
            - "fi"
            - "fr"
            - "gl"
            - "he"
            - "hi"
            - "hr"
            - "hsb"
            - "hu"
            - "hy"
            - "id"
            - "is"
            - "it"
            - "ja"
            - "km"
            - "ko"
            - "lt"
            - "lv"
            - "mk"
            - "ms"
            - "nb"
            - "nl"
            - "pl"
            - "ps"
            - "pt-BR"
            - "pt"
            - "ro"
            - "ru"
            - "sk"
            - "sl"
            - "sr-Cyrl"
            - "sr"
            - "sv"
            - "th"
            - "tr"
            - "uk"
            - "vi"
            - "zh-CN"
            - "zh-TW"

    wbw.core.asset.material_design_color_palette:
        version: "1.0.1"

    wbw.core.asset.material_design_hierarchical_display:
        version: "1.0.1"

    wbw.core.asset.material_design_iconic_font:
        version: "2.2.0"

    wbw.core.asset.sweet_alert:
        version: "2.1.2"

    wbw.core.asset.wait_me:
        version: "1.19"
