# Resources/config/assets.yml
assets:

    wbw.core.asset.core:
        plugins:
            animate_css:
                version: "3.7.0"
                description: "Animate.css"
                stylesheets:
                    - "/animate.css-{{ version }}/animate.min.css"
                javascripts: []
            clippy_js:
                version: ""
                description: "Clippy.js"
                stylesheets:
                    - "/clippy.js/clippy.css"
                javascripts:
                    - "/clippy.js/clippy.min.js"
            font_awesome:
                version: "5.12.0"
                description: "Font Awesome"
                stylesheets:
                    - "/fontawesome-{{ version }}/css/all.min.css"
                javascripts:
                    - "/fontawesome-{{ version }}/js/all.min.js"
            jquery:
                version: "3.4.1"
                description: "jQuery"
                stylesheets: []
                javascripts:
                    - "/jquery-{{ version }}/jquery-3.4.1.min.js"
            jquery_easy_autocomplete:
                version: "1.3.4"
                description: "jQuery EasyAutoComplete"
                stylesheets:
                    - "/jquery-easyautocomplete-{{ version }}/easy-autocomplete.min.css"
                    - "/jquery-easyautocomplete-{{ version }}/easy-autocomplete.themes.min.css"
                javascripts:
                    - "/jquery-easyautocomplete-{{ version }}/jquery.easy-autocomplete.min.js"
            jquery_input_mask:
                version: "3.3.11"
                description: "jQuery InputMask"
                stylesheets: []
                javascripts:
                    - "/jquery-inputmask-{{ version }}/min/jquery.inputmask.bundle.min.js"
            jquery_select2:
                version: "4.0.5"
                description: "jQuery Select2"
                stylesheets:
                    - "/jquery-select2-{{ version }}/css/select2.min.css"
                javascripts:
                    - "/jquery-select2-{{ version }}/js/select2.min.js"
                    - "/jquery-select2-{{ version }}/js/i18n/{{ locale }}.js"
                locales:
                    - "af"
                    - "ar"
                    - "az"
                    - "bg"
                    - "bs"
                    - "ca"
                    - "cs"
                    - "da"
                    - "de"
                    - "dsb"
                    - "el"
                    - "en"
                    - "es"
                    - "et"
                    - "eu"
                    - "fa"
                    - "fi"
                    - "fr"
                    - "gl"
                    - "he"
                    - "hi"
                    - "hr"
                    - "hsb"
                    - "hu"
                    - "hy"
                    - "id"
                    - "is"
                    - "it"
                    - "ja"
                    - "km"
                    - "ko"
                    - "lt"
                    - "lv"
                    - "mk"
                    - "ms"
                    - "nb"
                    - "nl"
                    - "pl"
                    - "ps"
                    - "pt-BR"
                    - "pt"
                    - "ro"
                    - "ru"
                    - "sk"
                    - "sl"
                    - "sr-Cyrl"
                    - "sr"
                    - "sv"
                    - "th"
                    - "tr"
                    - "uk"
                    - "vi"
                    - "zh-CN"
                    - "zh-TW"
            material_design_color_palette:
                version: "1.1.0"
                description: "Material Design Color Palette"
                stylesheets:
                    - "/material-design-color-palette-{{ version }}/material-design-color-palette.min.css"
                javascripts: []
            material_design_hierarchical_display:
                version: "1.0.1"
                description: "Material Design Hierarchical Display"
                stylesheets:
                    - "/material-design-hierarchical-display-{{ version }}/zmd.hierarchical-display.min.css"
                javascripts:
                    - "/material-design-hierarchical-display-{{ version }}/jquery.zmd.hierarchical-display.min.js"
            material_design_iconic_font:
                version: "2.2.0"
                description: "Material Design Iconic Font"
                stylesheets:
                    - "/material-design-iconic-font-{{ version }}/css/material-design-iconic-font.min.css"
                javascripts: []
            meteocons:
                version: ""
                description: "Meteocons"
                stylesheets:
                    - "/meteocons/stylesheet.css"
                    - "/css/meteocons.css"
                javascripts: []
            sweet_alert:
                version: "2.1.2"
                description: "SweetAlert"
                stylesheets: []
                javascripts:
                    - "/sweetalert-{{ version }}/sweetalert.min.js"
            syntax_highlighter:
                version: "3.0.83"
                description: "SyntaxHighlighter"
                stylesheets:
                    - "/syntaxhighlighter-{{ version }}/styles/shCore.css"
                    - "/syntaxhighlighter-{{ version }}/styles/shTheme{{ theme }}.css"
                javascripts:
                    - "/syntaxhighlighter-{{ version }}/scripts/XRegExp.js"
                    - "/syntaxhighlighter-{{ version }}/scripts/shCore.js"
                    - "/syntaxhighlighter-{{ version }}/scripts/shAutoloader.js"
                    - "/syntaxhighlighter-{{ version }}/scripts/shLegacy.js"
                brushes:
                    - "AppleScript"
                    - "AS3"
                    - "Bash"
                    - "ColdFusion"
                    - "Cpp"
                    - "CSharp"
                    - "Css"
                    - "Delphi"
                    - "Diff"
                    - "Erlang"
                    - "Groovy"
                    - "Java"
                    - "JavaFX"
                    - "JScript"
                    - "Perl"
                    - "Php"
                    - "Plain"
                    - "PowerShell"
                    - "Python"
                    - "Ruby"
                    - "Sass"
                    - "Scala"
                    - "Sql"
                    - "Vb"
                    - "Xml"
                themes:
                    - "Default"
                    - "Django"
                    - "Eclipse"
                    - "Emacs"
                    - "FadeToGrey"
                    - "MDUltra"
                    - "Midnight"
                    - "RDark"
            wait_me:
                version: "1.19"
                description: "waitMe"
                stylesheets:
                    - "/waitme-{{ version }}/waitMe.min.css"
                javascripts:
                    - "/waitme-{{ version }}/waitMe.min.js"
