# Resources/config/commands.yml
services:

    wbw.core.command.copy_skeleton:
        class:  WBW\Bundle\CoreBundle\Command\CopySkeletonCommand
        public: false
        tags:
            - { name: "console.command" }

    wbw.core.command.unzip_assets:
        class:  WBW\Bundle\CoreBundle\Command\UnzipAssetsCommand
        public: false
        tags:
            - { name: "console.command" }
