# Resources/config/commands.yml
services:

    wbw.core.command.copy_skeleton:
        class: WBW\Bundle\CoreBundle\Command\CopySkeletonCommand
        public:    true
        tags:
            - { name: "console.command" }

    wbw.core.command.unzip_assets:
        class: WBW\Bundle\CoreBundle\Command\UnzipAssetsCommand
        public:    true
        tags:
            - { name: "console.command" }
