# Resources/config/controllers.yml
services:

    WBW\Bundle\CoreBundle\Controller\HostController:
        alias:  "wbw.core.controller.host"
        public: true

    wbw.core.controller.host:
        class: WBW\Bundle\CoreBundle\Controller\HostController
        calls:
            - [ "setContainer", [ "@Psr\\Container\\ContainerInterface" ] ]
        tags:
            - { name: "container.service_subscriber" }

    WBW\Bundle\CoreBundle\Controller\TwigController:
        alias:  "wbw.core.controller.twig"
        public: true

    wbw.core.controller.twig:
        class: WBW\Bundle\CoreBundle\Controller\TwigController
        calls:
            - [ "setContainer",         [ "@Psr\\Container\\ContainerInterface" ] ]
            - [ "setJavascriptManager", [ "@wbw.core.manager.javascript" ] ]
            - [ "setStylesheetManager", [ "@wbw.core.manager.stylesheet" ] ]
        tags:
            - { name: "container.service_subscriber" }
