# Resources/config/providers.yml
services:

    wbw.core.provider.javascript:
        class:  WBW\Bundle\CoreBundle\Provider\JavascriptProvider
        public: false
        tags:
            - { name: "wbw.core.provider.javascript" }

    wbw.core.provider.syntax_highlighter:
        class:  WBW\Bundle\CoreBundle\Provider\SyntaxHighlighterProvider
        public: false
        arguments: [ "@translator" ]
