# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.command.unzip_assets:
        class: WBW\Bundle\CoreBundle\Command\UnzipAssetsCommand
        tags:
            - { name: "console.command" }

    wbw.core.event_listener.kernel:
        class:     WBW\Bundle\CoreBundle\EventListener\KernelEventListener
        arguments: ["@security.token_storage", "@wbw.core.manager.theme"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException" }
            - { name: "kernel.event_listener", event: "kernel.request",   method: "onKernelRequest" }

    wbw.core.event_listener.notification:
        class:     WBW\Bundle\CoreBundle\EventListener\NotificationEventListener
        arguments: ["@session"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "wbw.core.event.notification.danger",  method: "onNotify" }
            - { name: "kernel.event_listener", event: "wbw.core.event.notification.info",    method: "onNotify" }
            - { name: "kernel.event_listener", event: "wbw.core.event.notification.success", method: "onNotify" }
            - { name: "kernel.event_listener", event: "wbw.core.event.notification.warning", method: "onNotify" }

    wbw.core.helper.form:
        class:     WBW\Bundle\CoreBundle\Helper\FormHelper
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]
        public:    true

    wbw.core.manager.color:
        class:  WBW\Bundle\CoreBundle\Manager\ColorManager
        public: true

    wbw.core.manager.quote:
        class:  WBW\Bundle\CoreBundle\Manager\QuoteManager
        public: true

    wbw.core.manager.theme:
        class:     WBW\Bundle\CoreBundle\Manager\ThemeManager
        arguments: ["@twig"]
        public:    true
        calls:
            - ["setApplicationThemeProvider",           ["@?wbw.core.provider.theme.application"]]
            - ["setBreadcrumbsThemeProvider",           ["@?wbw.core.provider.theme.breadcrumbs"]]
            - ["setHookDropDownThemeProvider",          ["@?wbw.core.provider.theme.hook_drop_down"]]
            - ["setFooterThemeProvider",                ["@?wbw.core.provider.theme.footer"]]
            - ["setNavigationThemeProvider",            ["@?wbw.core.provider.theme.navigation"]]
            - ["setNotificationsDropDownThemeProvider", ["@?wbw.core.provider.theme.notifications_drop_down"]]
            - ["setSearchThemeProvider",                ["@?wbw.core.provider.theme.search"]]
            - ["setTasksDropDownThemeProvider",         ["@?wbw.core.provider.theme.tasks_drop_down"]]
            - ["setUserInfoThemeProvider",              ["@?wbw.core.provider.theme.user_info"]]

    wbw.core.provider.color.amber:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\AmberColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.blue:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BlueColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.blue_grey:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BlueGreyColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.brown:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BrownColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.cyan:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\CyanColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.deep_orange:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\DeepOrangeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.deep_purple:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\DeepPurpleColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.green:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\GreenColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.grey:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\GreyColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.indigo:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\IndigoColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.light_blue:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LightBlueColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.light_green:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LightGreenColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.lime:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LimeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.orange:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\OrangeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.pink:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\PinkColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.purple:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\PurpleColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.red:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\RedColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.teal:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\TealColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.yellow:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\YellowColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.twig.extension.plugin.font_awesome:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\FontAwesomeTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.jquery_inputmask:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\JQueryInputMaskTwigExtension
        arguments: ["@twig", "@wbw.core.twig.extension.renderer"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.material_design_color_palette:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MaterialDesignColorPaletteTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.material_design_iconic_font:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MaterialDesignIconicFontTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.meteocons:
        class:      WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MeteoconsTwigExtension
        arguments: ["@twig"]
        public:     true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.quote:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\QuoteTwigExtension
        arguments: ["@twig", "@wbw.core.manager.quote"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.renderer:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\RendererTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.stylesheet:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\StylesheetTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.utility:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\UtilityTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }
