# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    WBW\Bundle\CoreBundle\Controller\TwigController:
        alias:  "wbw.core.controller.twig"
        public: true

    wbw.core.component.form.helper:
        class:  WBW\Bundle\CoreBundle\Component\Form\FormHelper
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]
        public: true

    wbw.core.controller.twig:
        class: WBW\Bundle\CoreBundle\Controller\TwigController
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    wbw.core.manager.assets.color:
        class:  WBW\Library\Symfony\Manager\Assets\ColorManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.assets.quote:
        class:  WBW\Library\Symfony\Manager\Assets\QuoteManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.asset.theme:
        class:  WBW\Bundle\CoreBundle\Manager\Asset\ThemeManager
        arguments: [ "@logger", "@twig" ]
        public: true
        calls:
            - [ "setApplicationThemeProvider",           [ "@?wbw.core.provider.theme.application" ] ]
            - [ "setBreadcrumbsThemeProvider",           [ "@?wbw.core.provider.theme.breadcrumbs" ] ]
            - [ "setHookDropDownThemeProvider",          [ "@?wbw.core.provider.theme.hook_drop_down" ] ]
            - [ "setFooterThemeProvider",                [ "@?wbw.core.provider.theme.footer" ] ]
            - [ "setNavigationThemeProvider",            [ "@?wbw.core.provider.theme.navigation" ] ]
            - [ "setNotificationsDropDownThemeProvider", [ "@?wbw.core.provider.theme.notifications_drop_down" ] ]
            - [ "setSearchThemeProvider",                [ "@?wbw.core.provider.theme.search" ] ]
            - [ "setTasksDropDownThemeProvider",         [ "@?wbw.core.provider.theme.tasks_drop_down" ] ]
            - [ "setUserInfoThemeProvider",              [ "@?wbw.core.provider.theme.user_info" ] ]

    wbw.core.repository.repository_helper:
        class:  WBW\Bundle\CoreBundle\Repository\RepositoryHelper
        arguments: [ "@doctrine.orm.entity_manager" ]
        public: true

    wbw.core.twig.extension.container:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\ContainerTwigExtension
        arguments: [ "@service_container" ]
        public: true
        tags:
            - { name: "twig.extension" }
