# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.helper.form:
        class:  WBW\Bundle\CoreBundle\Helper\FormHelper
        public: false
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]

    WBW\Bundle\CoreBundle\Service\SymfonyBCService:
        alias:  "wbw.core.service.compatibility"
        public: false

    wbw.core.service.compatibility:
        class:  WBW\Bundle\CoreBundle\Service\SymfonyBCService
        public: true
        arguments: [ "@service_container" ]

    wbw.core.service.repository:
        class:  WBW\Bundle\CoreBundle\Service\RepositoryService
        public: false
        calls:
            - [ "setStatementService", [ "@wbw.core.service.statement" ] ]

    wbw.core.service.statement:
        class:  WBW\Bundle\CoreBundle\Service\StatementService
        public: false
        arguments: [ "@doctrine.orm.entity_manager" ]

    wbw.core.service.token_generator:
        class:  WBW\Library\Symfony\Service\TokenGeneratorService
        public: false

    wbw.core.twig.extension.container:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\ContainerTwigExtension
        public: false
        arguments: [ "@twig", "@service_container" ]
        tags:
            - { name: "twig.extension" }
