# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.component.form.helper:
        class:  WBW\Bundle\CoreBundle\Component\Form\FormHelper
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]
        public: true

    wbw.core.manager.asset.color:
        class:  WBW\Bundle\CoreBundle\Manager\Asset\ColorManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.asset.quote:
        class:  WBW\Bundle\CoreBundle\Manager\Asset\QuoteManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.asset.theme:
        class:  WBW\Bundle\CoreBundle\Manager\Asset\ThemeManager
        arguments: [ "@logger", "@twig" ]
        public: true
        calls:
            - [ "setApplicationThemeProvider",           [ "@?wbw.core.provider.theme.application" ] ]
            - [ "setBreadcrumbsThemeProvider",           [ "@?wbw.core.provider.theme.breadcrumbs" ] ]
            - [ "setHookDropDownThemeProvider",          [ "@?wbw.core.provider.theme.hook_drop_down" ] ]
            - [ "setFooterThemeProvider",                [ "@?wbw.core.provider.theme.footer" ] ]
            - [ "setNavigationThemeProvider",            [ "@?wbw.core.provider.theme.navigation" ] ]
            - [ "setNotificationsDropDownThemeProvider", [ "@?wbw.core.provider.theme.notifications_drop_down" ] ]
            - [ "setSearchThemeProvider",                [ "@?wbw.core.provider.theme.search" ] ]
            - [ "setTasksDropDownThemeProvider",         [ "@?wbw.core.provider.theme.tasks_drop_down" ] ]
            - [ "setUserInfoThemeProvider",              [ "@?wbw.core.provider.theme.user_info" ] ]

    wbw.core.repository.repository_helper:
        class:  WBW\Bundle\CoreBundle\Repository\RepositoryHelper
        arguments: [ "@doctrine.orm.entity_manager" ]
        public: true

    wbw.core.twig.extension.container:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\ContainerTwigExtension
        arguments: [ "@service_container" ]
        public: true
        tags:
            - { name: "twig.extension" }

    wbw.core.utility.canonical_fields_updater.default:
        class:  WBW\Bundle\CoreBundle\Utility\CanonicalFieldsUpdater
        arguments: [ "@wbw.core.utility.canonicalizer.default", "@wbw.core.utility.canonicalizer.default" ]
        public: false

    wbw.core.utility.canonicalizer.default:
        class:  WBW\Bundle\CoreBundle\Utility\Canonicalizer
        public: false

    wbw.core.utility.password_updater.default:
        class:  WBW\Bundle\CoreBundle\Utility\PasswordUpdater
        arguments: [ "@security.encoder_factory" ]
        public: false

    wbw.core.utility.token_generator.default:
        class:  WBW\Bundle\CoreBundle\Utility\TokenGenerator
        public: false

    wbw.core.validator.initializer:
        class:  WBW\Bundle\CoreBundle\Validator\Initializer
        arguments: [ "@wbw.core.utility.canonical_fields_updater.default" ]
        public: false
