# Resources/config/services.yml
services:

    logger:
        alias: "monolog.logger"
        public: true

    webeweb.core.eventlistener.kernel:
        class:     WBW\Bundle\CoreBundle\EventListener\KernelEventListener
        arguments: ["@security.token_storage", "@webeweb.core.manager.theme"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException" }
            - { name: "kernel.event_listener", event: "kernel.request",   method: "onKernelRequest" }

    webeweb.core.eventlistener.notification:
        class:     WBW\Bundle\CoreBundle\EventListener\NotificationEventListener
        arguments: ["@session"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "webeweb.core.event.notification.danger",  method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.core.event.notification.info",    method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.core.event.notification.success", method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.core.event.notification.warning", method: "onNotify" }

    webeweb.core.manager.theme:
        class:     WBW\Bundle\CoreBundle\Manager\ThemeManager
        arguments: ["@twig"]
        public:    true
        calls:
            - ["setApplicationThemeProvider",           ["@?webeweb.core.provider.theme.application"]]
            - ["setBreadcrumbsThemeProvider",           ["@?webeweb.core.provider.theme.breadcrumbs"]]
            - ["setHookDropDownThemeProvider",          ["@?webeweb.core.provider.theme.hook_drop_down"]]
            - ["setFooterThemeProvider",                ["@?webeweb.core.provider.theme.footer"]]
            - ["setNavigationThemeProvider",            ["@?webeweb.core.provider.theme.navigation"]]
            - ["setNotificationsDropDownThemeProvider", ["@?webeweb.core.provider.theme.notifications_drop_down"]]
            - ["setSearchThemeProvider",                ["@?webeweb.core.provider.theme.search"]]
            - ["setTasksDropDownThemeProvider",         ["@?webeweb.core.provider.theme.tasks_drop_down"]]
            - ["setUserInfoThemeProvider",              ["@?webeweb.core.provider.theme.user_info"]]

    webeweb.core.twig.extension.plugin.font_awesome:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\FontAwesomeTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    webeweb.core.twig.extension.plugin.jquery_inputmask:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\JQueryInputMaskTwigExtension
        arguments: ["@twig", "@webeweb.core.twig.extension.renderer"]
        public:    true
        tags:
            - { name: "twig.extension" }

    webeweb.core.twig.extension.plugin.material_design_iconic_font:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MaterialDesignIconicFontTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    webeweb.core.twig.extension.plugin.meteocons:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MeteoconsTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    webeweb.core.twig.extension.renderer:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\RendererTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }
