# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.helper.form:
        class:     WBW\Bundle\CoreBundle\Helper\FormHelper
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]
        public:    true

    wbw.core.helper.repository_report:
        class:     WBW\Bundle\CoreBundle\Helper\RepositoryReportHelper
        arguments: ["@doctrine.orm.entity_manager"]
        public:    true

    wbw.core.manager.color:
        class:     WBW\Bundle\CoreBundle\Manager\ColorManager
        public:    true
        arguments: ["@logger"]

    wbw.core.manager.quote:
        class:     WBW\Bundle\CoreBundle\Manager\QuoteManager
        public:    true
        arguments: ["@logger"]

    wbw.core.manager.theme:
        class:     WBW\Bundle\CoreBundle\Manager\ThemeManager
        arguments: ["@logger", "@twig"]
        public:    true
        calls:
            - ["setApplicationThemeProvider",           ["@?wbw.core.provider.theme.application"]]
            - ["setBreadcrumbsThemeProvider",           ["@?wbw.core.provider.theme.breadcrumbs"]]
            - ["setHookDropDownThemeProvider",          ["@?wbw.core.provider.theme.hook_drop_down"]]
            - ["setFooterThemeProvider",                ["@?wbw.core.provider.theme.footer"]]
            - ["setNavigationThemeProvider",            ["@?wbw.core.provider.theme.navigation"]]
            - ["setNotificationsDropDownThemeProvider", ["@?wbw.core.provider.theme.notifications_drop_down"]]
            - ["setSearchThemeProvider",                ["@?wbw.core.provider.theme.search"]]
            - ["setTasksDropDownThemeProvider",         ["@?wbw.core.provider.theme.tasks_drop_down"]]
            - ["setUserInfoThemeProvider",              ["@?wbw.core.provider.theme.user_info"]]
