# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.helper.form:
        class:     WBW\Bundle\CoreBundle\Helper\FormHelper
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]
        public:    true

    wbw.core.manager.color:
        class:  WBW\Bundle\CoreBundle\Manager\ColorManager
        public: true

    wbw.core.manager.quote:
        class:  WBW\Bundle\CoreBundle\Manager\QuoteManager
        public: true

    wbw.core.manager.theme:
        class:     WBW\Bundle\CoreBundle\Manager\ThemeManager
        arguments: ["@twig"]
        public:    true
        calls:
            - ["setApplicationThemeProvider",           ["@?wbw.core.provider.theme.application"]]
            - ["setBreadcrumbsThemeProvider",           ["@?wbw.core.provider.theme.breadcrumbs"]]
            - ["setHookDropDownThemeProvider",          ["@?wbw.core.provider.theme.hook_drop_down"]]
            - ["setFooterThemeProvider",                ["@?wbw.core.provider.theme.footer"]]
            - ["setNavigationThemeProvider",            ["@?wbw.core.provider.theme.navigation"]]
            - ["setNotificationsDropDownThemeProvider", ["@?wbw.core.provider.theme.notifications_drop_down"]]
            - ["setSearchThemeProvider",                ["@?wbw.core.provider.theme.search"]]
            - ["setTasksDropDownThemeProvider",         ["@?wbw.core.provider.theme.tasks_drop_down"]]
            - ["setUserInfoThemeProvider",              ["@?wbw.core.provider.theme.user_info"]]

    wbw.core.provider.color.amber:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\AmberColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.blue:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BlueColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.blue_grey:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BlueGreyColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.brown:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\BrownColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.cyan:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\CyanColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.deep_orange:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\DeepOrangeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.deep_purple:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\DeepPurpleColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.green:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\GreenColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.grey:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\GreyColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.indigo:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\IndigoColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.light_blue:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LightBlueColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.light_green:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LightGreenColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.lime:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\LimeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.orange:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\OrangeColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.pink:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\PinkColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.purple:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\PurpleColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.red:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\RedColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.teal:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\TealColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }

    wbw.core.provider.color.yellow:
        class:  WBW\Bundle\CoreBundle\Color\MaterialDesignColorPalette\YellowColorProvider
        public: true
        tags:
            - { name: "wbw.core.provider.color" }
