# Resources/config/services.yml
services:

    logger:
        alias:  "monolog.logger"
        public: true

    wbw.core.helper.form:
        class:  WBW\Bundle\CoreBundle\Helper\FormHelper
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]
        public: true

    wbw.core.manager.color:
        class:  WBW\Library\Symfony\Manager\ColorManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.javascript:
        class:  WBW\Library\Symfony\Manager\JavascriptManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.quote:
        class:  WBW\Library\Symfony\Manager\QuoteManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.stylesheet:
        class:  WBW\Library\Symfony\Manager\StylesheetManager
        arguments: [ "@logger" ]
        public: true

    wbw.core.manager.theme:
        class:  WBW\Bundle\CoreBundle\Manager\ThemeManager
        arguments: [ "@logger", "@twig" ]
        public: true
        calls:
            - [ "setApplicationThemeProvider",           [ "@?wbw.core.provider.theme.application" ] ]
            - [ "setBreadcrumbsThemeProvider",           [ "@?wbw.core.provider.theme.breadcrumbs" ] ]
            - [ "setHookDropdownThemeProvider",          [ "@?wbw.core.provider.theme.hook_dropdown" ] ]
            - [ "setFooterThemeProvider",                [ "@?wbw.core.provider.theme.footer" ] ]
            - [ "setNavigationThemeProvider",            [ "@?wbw.core.provider.theme.navigation" ] ]
            - [ "setNotificationsDropdownThemeProvider", [ "@?wbw.core.provider.theme.notifications_dropdown" ] ]
            - [ "setSearchThemeProvider",                [ "@?wbw.core.provider.theme.search" ] ]
            - [ "setTasksDropdownThemeProvider",         [ "@?wbw.core.provider.theme.tasks_dropdown" ] ]
            - [ "setUserInfoThemeProvider",              [ "@?wbw.core.provider.theme.user_info" ] ]

    wbw.core.repository.repository_helper:
        alias:  "wbw.core.service.repository"
        public: true

    wbw.core.service.repository:
        class:  WBW\Bundle\CoreBundle\Service\RepositoryService
        public: true
        calls:
            - [ "setStatementService", [ "@wbw.core.service.statement" ] ]

    wbw.core.service.statement:
        class:  WBW\Bundle\CoreBundle\Service\StatementService
        arguments: [ "@doctrine.orm.entity_manager" ]
        public: true

    wbw.core.service.token_generator:
        class:  WBW\Library\Symfony\Service\TokenGeneratorService
        public: true

    wbw.core.twig.extension.container:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\ContainerTwigExtension
        arguments: [ "@twig", "@service_container" ]
        public: true
        tags:
            - { name: "twig.extension" }
