# Resources/config/twig.yml
services:

    wbw.core.twig.extension.assets:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\AssetsTwigExtension
        public: false
        arguments: [ "@twig" ]
        calls:
            - [ "setPublicDirectory", [ "%kernel.project_dir%/public" ] ]
            - [ "setRouter",          [ "@router" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.font_awesome:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\FontAwesomeTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.jquery_inputmask:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\JQueryInputMaskTwigExtension
        public: false
        arguments: [ "@twig", "@wbw.core.twig.extension.assets" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.material_design_color_palette:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\MaterialDesignColorPaletteTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.material_design_iconic_font:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\MaterialDesignIconicFontTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.meteocons:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\MeteoconsTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.assets.syntax_highlighter:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\Assets\SyntaxHighlighterTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.quote:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\QuoteTwigExtension
        public: false
        arguments: [ "@twig", "@wbw.core.manager.quote" ]
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.string:
        class:  WBW\Bundle\CoreBundle\Twig\Extension\StringTwigExtension
        public: false
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }
