# Resources/config/twig.yml
services:

    wbw.core.twig.extension.plugin.font_awesome:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\FontAwesomeTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.jquery_inputmask:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\JQueryInputMaskTwigExtension
        arguments: ["@twig", "@wbw.core.twig.extension.renderer"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.material_design_color_palette:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MaterialDesignColorPaletteTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.material_design_iconic_font:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MaterialDesignIconicFontTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.plugin.meteocons:
        class:      WBW\Bundle\CoreBundle\Twig\Extension\Plugin\MeteoconsTwigExtension
        arguments: ["@twig"]
        public:     true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.quote:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\QuoteTwigExtension
        arguments: ["@twig", "@wbw.core.manager.quote"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.renderer:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\RendererTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.stylesheet:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\StylesheetTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }

    wbw.core.twig.extension.utility:
        class:     WBW\Bundle\CoreBundle\Twig\Extension\UtilityTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }
