# Resources/config/services/security_event_listeners.yml
services:

    wbw.core.event_listener.security:
        class:  WBW\Bundle\CoreBundle\EventListener\SecurityEventListener
        arguments: [ "@translator", "@=service('wbw.core.event_listener.kernel').getUser()" ]
        public: true
        tags:
            - { name: "kernel.event_listener", event: "security.interactive_login", method: "onInteractiveLogin" }
