# Resources/config/services/services_profile.yml
services:

    wbw.core.controller.profile:
        class:  WBW\Bundle\CoreBundle\Controller\ProfileController
        arguments: [ "@wbw.core.form.factory.profile", "@wbw.core.manager.user.default" ]
        public: false

    wbw.core.form.factory.profile:
        class:  WBW\Bundle\CoreBundle\Form\Factory\FormFactory
        arguments: [ "@form.factory", "%wbw_core.user.profile.form.name%", "%wbw_core.user.profile.form.type%", "%wbw_core.user.profile.form.validation_groups%" ]
        public: false

    wbw.core.form.type.profile:
        class:  WBW\Bundle\CoreBundle\Form\Type\ProfileFormType
        arguments: [ "%wbw_core.user.user_class%" ]
        public: false
        tags:
            - { name: "form.type" }
