# Resources/config/services/services_group.yml
services:

    wbw.core.controller.group:
        class:  WBW\Bundle\CoreBundle\Controller\GroupController
        arguments: [ "@wbw.core.form.factory.group", "@wbw.core.manager.group.default" ]
        public: false

    wbw.core.form.factory.group:
        class:  WBW\Bundle\CoreBundle\Form\Factory\FormFactory
        arguments: [ "@form.factory", "%wbw_core.user.group.form.name%", "%wbw_core.user.group.form.type%", "%wbw_core.user.group.form.validation_groups%" ]
        public: false

    wbw.core.form.type.group:
        class:  WBW\Bundle\CoreBundle\Form\Type\GroupFormType
        arguments: [ "%wbw_core.user.group.class%" ]
        public: false
        tags:
            - { name: "form.type" }
