# Resources/config/services/services_change_password.yml
services:

    wbw.core.controller.change_password:
        class:  WBW\Bundle\CoreBundle\Controller\ChangePasswordController
        arguments: [ "@wbw.core.form.factory.change_password", "@wbw.core.manager.user.default" ]
        public: false

    wbw.core.form.factory.change_password:
        class:  WBW\Bundle\CoreBundle\Form\Factory\FormFactory
        arguments: [ "@form.factory", "%wbw_core.user.change_password.form.name%", "%wbw_core.user.change_password.form.type%", "%wbw_core.user.change_password.form.validation_groups%" ]
        public: false

    wbw.core.form.type.change_password:
        class:  WBW\Bundle\CoreBundle\Form\Type\ChangePasswordFormType
        arguments: [ "%wbw_core.user.user_class%" ]
        public: false
        tags:
            - { name: "form.type" }
