# Resources/config/services/worlds_wisdom_quote_provider.yml
services:

    wbw.core.provider.quote.worlds_wisdom:
        class: WBW\Bundle\CoreBundle\Asset\Quote\YamlQuoteProvider
        arguments: [ "@=service('kernel').locateResource('@WBWCoreBundle/Resources/translations/WorldsWisdom.fr.yml')" ]
        tags:
            - { name: "wbw.core.provider.quote" }
