# Resources/config/services/worlds_wisdom_quote_provider.yml
services:

    wbw.core.provider.quote.worlds_wisdom:
        class:     WBW\Bundle\CoreBundle\Quote\YamlQuoteProvider
        arguments: ["%kernel.root_dir%/../vendor/webeweb/core-bundle/Resources/translations/WorldsWisdom.fr.yml"]
        tags:
            - { name: "wbw.core.provider.quote" }
