# Resources/config/quote/worlds_wisdom.yml
services:

    wbw.core.provider.quote.worlds_wisdom:
        class: WBW\Library\Symfony\Provider\Quote\WorldsWisdomQuoteProvider
        tags:
            - { name: "wbw.core.provider.quote" }
