# Resources/config/quote/worlds_wisdom.yml
services:

    wbw.core.provider.assets.quote.worlds_wisdom:
        class: WBW\Library\Symfony\Assets\Quote\WorldsWisdomQuoteProvider
        tags:
            - { name: "wbw.core.provider.assets.quote" }
